FROM alpine:3.6
ENV container docker
MAINTAINER "Levent SAGIROGLU" <LSagiroglu@gmail.com>

ENV USER_EMAIL ""


RUN apk update && \
    apk upgrade && \
    apk add --no-cache git curl wget nano && \	
	apk add ca-certificates && \
	update-ca-certificates

RUN git config --global user.email USER_EMAIL

VOLUME /WORK

WORKDIR /WORK

CMD ["/bin/sh"]
